/**
 * @file SelectedBoard.hpp
 * @brief Single-source compile-time metadata for the selected board.
 */

#pragma once

#include "panels/PanelDescriptor.hpp"
#include "services/board/BoardDescriptor.hpp"
#include "sdkconfig.h"

#if defined(CONFIG_INKPLATE_BOARD_INKPLATE2)
#define PROSTOKONT_BOARD_PANEL_HEADER "panels/inkplate/Inkplate2.h"
#define PROSTOKONT_BOARD_PANEL_CLASS Inkplate2
#define PROSTOKONT_BOARD_KEY "inkplate-2"
#define PROSTOKONT_BOARD_NAME "Inkplate 2"
#define PROSTOKONT_PANEL_KEY "inkplate-2-panel"
#define PROSTOKONT_PANEL_MANUFACTURER "Soldered"
#define PROSTOKONT_PANEL_MODEL "Inkplate 2 tri-color"
#define PROSTOKONT_PANEL_WIDTH_MM 24
#define PROSTOKONT_PANEL_HEIGHT_MM 49
#define PROSTOKONT_PANEL_COLOR_KIND PANEL_COLOR_KIND_PALETTE
#define PROSTOKONT_PANEL_PARTIAL_UPDATE_SUPPORTED 0
#define PROSTOKONT_BOARD_COLOR_SCHEME "3-color"
#define PROSTOKONT_BOARD_COLOR_IMAGE 1
#define PROSTOKONT_BOARD_PACKED_FRAME_SUPPORTED 1
#define PROSTOKONT_BOARD_DEFAULT_ROTATION 3
#define PROSTOKONT_BOARD_PREFER_REDUCED_DITHER 0
#define PROSTOKONT_BOARD_ACCENT_COLOR 0
#define PROSTOKONT_BOARD_ERROR_COLOR 0
#define PROSTOKONT_BOARD_COMMUNICATION_PROTOCOLS                                  \
  (BOARD_PROTOCOL_SPI | BOARD_PROTOCOL_BLE | BOARD_PROTOCOL_WIFI_STA |            \
   BOARD_PROTOCOL_WIFI_SOFTAP | BOARD_PROTOCOL_HTTP | BOARD_PROTOCOL_MDNS)
#define PROSTOKONT_BOARD_SENSORS 0u
#define PROSTOKONT_BOARD_POWER_FEATURES (BOARD_POWER_USB | BOARD_POWER_PANEL_GATE)
#define PROSTOKONT_FIRMWARE_MODEL "prostokont-inkplate-2"
#elif defined(CONFIG_INKPLATE_BOARD_INKPLATE4)
#define PROSTOKONT_BOARD_PANEL_HEADER "panels/inkplate/Inkplate4.h"
#define PROSTOKONT_BOARD_PANEL_CLASS Inkplate4
#define PROSTOKONT_BOARD_KEY "inkplate-4"
#define PROSTOKONT_BOARD_NAME "Inkplate 4"
#define PROSTOKONT_PANEL_KEY "inkplate-4-panel"
#define PROSTOKONT_PANEL_MANUFACTURER "Soldered"
#define PROSTOKONT_PANEL_MODEL "Inkplate 4"
#define PROSTOKONT_PANEL_WIDTH_MM 85
#define PROSTOKONT_PANEL_HEIGHT_MM 85
#define PROSTOKONT_PANEL_COLOR_KIND PANEL_COLOR_KIND_GRAYSCALE
#define PROSTOKONT_PANEL_PARTIAL_UPDATE_SUPPORTED 1
#define PROSTOKONT_BOARD_COLOR_SCHEME "monochrome"
#define PROSTOKONT_BOARD_COLOR_IMAGE 0
#define PROSTOKONT_BOARD_PACKED_FRAME_SUPPORTED 0
#define PROSTOKONT_BOARD_DEFAULT_ROTATION 1
#define PROSTOKONT_BOARD_PREFER_REDUCED_DITHER 0
#define PROSTOKONT_BOARD_ACCENT_COLOR 0
#define PROSTOKONT_BOARD_ERROR_COLOR 0
#define PROSTOKONT_BOARD_COMMUNICATION_PROTOCOLS                                  \
  (BOARD_PROTOCOL_SPI | BOARD_PROTOCOL_I2C | BOARD_PROTOCOL_BLE |                \
   BOARD_PROTOCOL_WIFI_STA | BOARD_PROTOCOL_WIFI_SOFTAP | BOARD_PROTOCOL_HTTP |  \
   BOARD_PROTOCOL_MDNS)
#define PROSTOKONT_BOARD_SENSORS                                                  \
  (BOARD_SENSOR_TOUCH | BOARD_SENSOR_RTC | BOARD_SENSOR_FUEL_GAUGE |             \
   BOARD_SENSOR_IMU | BOARD_SENSOR_AMBIENT | BOARD_SENSOR_ENVIRONMENTAL)
#define PROSTOKONT_BOARD_POWER_FEATURES                                           \
  (BOARD_POWER_USB | BOARD_POWER_BATTERY | BOARD_POWER_FUEL_GAUGE |              \
   BOARD_POWER_FRONTLIGHT | BOARD_POWER_PANEL_GATE)
#define PROSTOKONT_FIRMWARE_MODEL "prostokont-inkplate-4"
#elif defined(CONFIG_INKPLATE_BOARD_INKPLATE5)
#define PROSTOKONT_BOARD_PANEL_HEADER "panels/inkplate/Inkplate5.h"
#define PROSTOKONT_BOARD_PANEL_CLASS Inkplate5
#define PROSTOKONT_BOARD_KEY "inkplate-5"
#define PROSTOKONT_BOARD_NAME "Inkplate 5"
#define PROSTOKONT_PANEL_KEY "inkplate-5-panel"
#define PROSTOKONT_PANEL_MANUFACTURER "Soldered"
#define PROSTOKONT_PANEL_MODEL "Inkplate 5"
#define PROSTOKONT_PANEL_WIDTH_MM 111
#define PROSTOKONT_PANEL_HEIGHT_MM 63
#define PROSTOKONT_PANEL_COLOR_KIND PANEL_COLOR_KIND_GRAYSCALE
#define PROSTOKONT_PANEL_PARTIAL_UPDATE_SUPPORTED 1
#define PROSTOKONT_BOARD_COLOR_SCHEME "monochrome"
#define PROSTOKONT_BOARD_COLOR_IMAGE 0
#define PROSTOKONT_BOARD_PACKED_FRAME_SUPPORTED 0
#define PROSTOKONT_BOARD_DEFAULT_ROTATION 0
#define PROSTOKONT_BOARD_PREFER_REDUCED_DITHER 0
#define PROSTOKONT_BOARD_ACCENT_COLOR 0
#define PROSTOKONT_BOARD_ERROR_COLOR 0
#define PROSTOKONT_BOARD_COMMUNICATION_PROTOCOLS                                  \
  (BOARD_PROTOCOL_SPI | BOARD_PROTOCOL_I2C | BOARD_PROTOCOL_BLE |                \
   BOARD_PROTOCOL_WIFI_STA | BOARD_PROTOCOL_WIFI_SOFTAP | BOARD_PROTOCOL_HTTP |  \
   BOARD_PROTOCOL_MDNS)
#define PROSTOKONT_BOARD_SENSORS (BOARD_SENSOR_RTC)
#define PROSTOKONT_BOARD_POWER_FEATURES                                           \
  (BOARD_POWER_USB | BOARD_POWER_BATTERY | BOARD_POWER_PANEL_GATE)
#define PROSTOKONT_FIRMWARE_MODEL "prostokont-inkplate-5"
#elif defined(CONFIG_INKPLATE_BOARD_INKPLATE6)
#define PROSTOKONT_BOARD_PANEL_HEADER "panels/inkplate/Inkplate6.h"
#define PROSTOKONT_BOARD_PANEL_CLASS Inkplate6
#define PROSTOKONT_BOARD_KEY "inkplate-6"
#define PROSTOKONT_BOARD_NAME "Inkplate 6"
#define PROSTOKONT_PANEL_KEY "inkplate-6-panel"
#define PROSTOKONT_PANEL_MANUFACTURER "Soldered"
#define PROSTOKONT_PANEL_MODEL "Inkplate 6"
#define PROSTOKONT_PANEL_WIDTH_MM 122
#define PROSTOKONT_PANEL_HEIGHT_MM 91
#define PROSTOKONT_PANEL_COLOR_KIND PANEL_COLOR_KIND_GRAYSCALE
#define PROSTOKONT_PANEL_PARTIAL_UPDATE_SUPPORTED 1
#define PROSTOKONT_BOARD_COLOR_SCHEME "monochrome"
#define PROSTOKONT_BOARD_COLOR_IMAGE 0
#define PROSTOKONT_BOARD_PACKED_FRAME_SUPPORTED 0
#define PROSTOKONT_BOARD_DEFAULT_ROTATION 0
#define PROSTOKONT_BOARD_PREFER_REDUCED_DITHER 0
#define PROSTOKONT_BOARD_ACCENT_COLOR 0
#define PROSTOKONT_BOARD_ERROR_COLOR 0
#define PROSTOKONT_BOARD_COMMUNICATION_PROTOCOLS                                  \
  (BOARD_PROTOCOL_SPI | BOARD_PROTOCOL_I2C | BOARD_PROTOCOL_I2S |                \
   BOARD_PROTOCOL_BLE | BOARD_PROTOCOL_WIFI_STA | BOARD_PROTOCOL_WIFI_SOFTAP |   \
   BOARD_PROTOCOL_HTTP | BOARD_PROTOCOL_MDNS)
#define PROSTOKONT_BOARD_SENSORS (BOARD_SENSOR_RTC)
#define PROSTOKONT_BOARD_POWER_FEATURES                                           \
  (BOARD_POWER_USB | BOARD_POWER_BATTERY | BOARD_POWER_PANEL_GATE)
#define PROSTOKONT_FIRMWARE_MODEL "prostokont-inkplate-6"
#elif defined(CONFIG_INKPLATE_BOARD_INKPLATE6COLOR)
#define PROSTOKONT_BOARD_PANEL_HEADER "panels/inkplate/Inkplate6Color.h"
#define PROSTOKONT_BOARD_PANEL_CLASS Inkplate6Color
#define PROSTOKONT_BOARD_KEY "inkplate-6-color"
#define PROSTOKONT_BOARD_NAME "Inkplate 6 Color"
#define PROSTOKONT_PANEL_KEY "inkplate-6-color-panel"
#define PROSTOKONT_PANEL_MANUFACTURER "Soldered"
#define PROSTOKONT_PANEL_MODEL "Inkplate 6 Color"
#define PROSTOKONT_PANEL_WIDTH_MM 115
#define PROSTOKONT_PANEL_HEIGHT_MM 86
#define PROSTOKONT_PANEL_COLOR_KIND PANEL_COLOR_KIND_PALETTE
#define PROSTOKONT_PANEL_PARTIAL_UPDATE_SUPPORTED 0
#define PROSTOKONT_BOARD_COLOR_SCHEME "7-color"
#define PROSTOKONT_BOARD_COLOR_IMAGE 1
#define PROSTOKONT_BOARD_PACKED_FRAME_SUPPORTED 1
#define PROSTOKONT_BOARD_DEFAULT_ROTATION 2
#define PROSTOKONT_BOARD_PREFER_REDUCED_DITHER 0
#define PROSTOKONT_BOARD_ACCENT_COLOR 0
#define PROSTOKONT_BOARD_ERROR_COLOR 0
#define PROSTOKONT_BOARD_COMMUNICATION_PROTOCOLS                                  \
  (BOARD_PROTOCOL_SPI | BOARD_PROTOCOL_I2C | BOARD_PROTOCOL_BLE |                \
   BOARD_PROTOCOL_WIFI_STA | BOARD_PROTOCOL_WIFI_SOFTAP | BOARD_PROTOCOL_HTTP |  \
   BOARD_PROTOCOL_MDNS)
#define PROSTOKONT_BOARD_SENSORS (BOARD_SENSOR_RTC)
#define PROSTOKONT_BOARD_POWER_FEATURES                                           \
  (BOARD_POWER_USB | BOARD_POWER_BATTERY | BOARD_POWER_PANEL_GATE)
#define PROSTOKONT_FIRMWARE_MODEL "prostokont-inkplate-6-color"
#elif defined(CONFIG_INKPLATE_BOARD_INKPLATE6FLICK)
#define PROSTOKONT_BOARD_PANEL_HEADER "panels/inkplate/Inkplate6.h"
#define PROSTOKONT_BOARD_PANEL_CLASS Inkplate6
#define PROSTOKONT_BOARD_KEY "inkplate-6-flick"
#define PROSTOKONT_BOARD_NAME "Inkplate 6 Flick"
#define PROSTOKONT_PANEL_KEY "inkplate-6-flick-panel"
#define PROSTOKONT_PANEL_MANUFACTURER "Soldered"
#define PROSTOKONT_PANEL_MODEL "Inkplate 6 Flick"
#define PROSTOKONT_PANEL_WIDTH_MM 163
#define PROSTOKONT_PANEL_HEIGHT_MM 122
#define PROSTOKONT_PANEL_COLOR_KIND PANEL_COLOR_KIND_GRAYSCALE
#define PROSTOKONT_PANEL_PARTIAL_UPDATE_SUPPORTED 1
#define PROSTOKONT_BOARD_COLOR_SCHEME "monochrome"
#define PROSTOKONT_BOARD_COLOR_IMAGE 0
#define PROSTOKONT_BOARD_PACKED_FRAME_SUPPORTED 0
#define PROSTOKONT_BOARD_DEFAULT_ROTATION 0
#define PROSTOKONT_BOARD_PREFER_REDUCED_DITHER 0
#define PROSTOKONT_BOARD_ACCENT_COLOR 0
#define PROSTOKONT_BOARD_ERROR_COLOR 0
#define PROSTOKONT_BOARD_COMMUNICATION_PROTOCOLS                                  \
  (BOARD_PROTOCOL_SPI | BOARD_PROTOCOL_I2C | BOARD_PROTOCOL_I2S |                \
   BOARD_PROTOCOL_BLE | BOARD_PROTOCOL_WIFI_STA | BOARD_PROTOCOL_WIFI_SOFTAP |   \
   BOARD_PROTOCOL_HTTP | BOARD_PROTOCOL_MDNS)
#define PROSTOKONT_BOARD_SENSORS (BOARD_SENSOR_TOUCH | BOARD_SENSOR_RTC)
#define PROSTOKONT_BOARD_POWER_FEATURES                                           \
  (BOARD_POWER_USB | BOARD_POWER_BATTERY | BOARD_POWER_FRONTLIGHT |              \
   BOARD_POWER_PANEL_GATE)
#define PROSTOKONT_FIRMWARE_MODEL "prostokont-inkplate-6-flick"
#elif defined(CONFIG_INKPLATE_BOARD_INKPLATE10)
#define PROSTOKONT_BOARD_PANEL_HEADER "panels/inkplate/Inkplate10.h"
#define PROSTOKONT_BOARD_PANEL_CLASS Inkplate10
#define PROSTOKONT_BOARD_KEY "inkplate-10"
#define PROSTOKONT_BOARD_NAME "Inkplate 10"
#define PROSTOKONT_PANEL_KEY "inkplate-10-panel"
#define PROSTOKONT_PANEL_MANUFACTURER "Soldered"
#define PROSTOKONT_PANEL_MODEL "Inkplate 10"
#define PROSTOKONT_PANEL_WIDTH_MM 203
#define PROSTOKONT_PANEL_HEIGHT_MM 139
#define PROSTOKONT_PANEL_COLOR_KIND PANEL_COLOR_KIND_GRAYSCALE
#define PROSTOKONT_PANEL_PARTIAL_UPDATE_SUPPORTED 1
#define PROSTOKONT_BOARD_COLOR_SCHEME "monochrome"
#define PROSTOKONT_BOARD_COLOR_IMAGE 0
#define PROSTOKONT_BOARD_PACKED_FRAME_SUPPORTED 0
#define PROSTOKONT_BOARD_DEFAULT_ROTATION 0
#define PROSTOKONT_BOARD_PREFER_REDUCED_DITHER 0
#define PROSTOKONT_BOARD_ACCENT_COLOR 0
#define PROSTOKONT_BOARD_ERROR_COLOR 0
#define PROSTOKONT_BOARD_COMMUNICATION_PROTOCOLS                                  \
  (BOARD_PROTOCOL_SPI | BOARD_PROTOCOL_I2C | BOARD_PROTOCOL_BLE |                \
   BOARD_PROTOCOL_WIFI_STA | BOARD_PROTOCOL_WIFI_SOFTAP | BOARD_PROTOCOL_HTTP |  \
   BOARD_PROTOCOL_MDNS)
#define PROSTOKONT_BOARD_SENSORS (BOARD_SENSOR_RTC)
#define PROSTOKONT_BOARD_POWER_FEATURES                                           \
  (BOARD_POWER_USB | BOARD_POWER_BATTERY | BOARD_POWER_PANEL_GATE)
#define PROSTOKONT_FIRMWARE_MODEL "prostokont-inkplate-10"
#elif defined(CONFIG_INKPLATE_BOARD_INKPLATE13)
#define PROSTOKONT_BOARD_PANEL_HEADER "panels/inkplate/Inkplate13.h"
#define PROSTOKONT_BOARD_PANEL_CLASS Inkplate13
#define PROSTOKONT_BOARD_KEY "inkplate-13"
#define PROSTOKONT_BOARD_NAME "Inkplate 13"
#define PROSTOKONT_PANEL_KEY "inkplate-13-panel"
#define PROSTOKONT_PANEL_MANUFACTURER "Soldered"
#define PROSTOKONT_PANEL_MODEL "Inkplate 13"
#define PROSTOKONT_PANEL_WIDTH_MM 203
#define PROSTOKONT_PANEL_HEIGHT_MM 270
#define PROSTOKONT_PANEL_COLOR_KIND PANEL_COLOR_KIND_PALETTE
#define PROSTOKONT_PANEL_PARTIAL_UPDATE_SUPPORTED 0
#define PROSTOKONT_BOARD_COLOR_SCHEME "7-color"
#define PROSTOKONT_BOARD_COLOR_IMAGE 1
#define PROSTOKONT_BOARD_PACKED_FRAME_SUPPORTED 1
#define PROSTOKONT_BOARD_DEFAULT_ROTATION 0
#define PROSTOKONT_BOARD_PREFER_REDUCED_DITHER 0
#define PROSTOKONT_BOARD_ACCENT_COLOR 0
#define PROSTOKONT_BOARD_ERROR_COLOR 0
#define PROSTOKONT_BOARD_COMMUNICATION_PROTOCOLS                                  \
  (BOARD_PROTOCOL_SPI | BOARD_PROTOCOL_I2C | BOARD_PROTOCOL_BLE |                \
   BOARD_PROTOCOL_WIFI_STA | BOARD_PROTOCOL_WIFI_SOFTAP | BOARD_PROTOCOL_HTTP |  \
   BOARD_PROTOCOL_MDNS)
#define PROSTOKONT_BOARD_SENSORS (BOARD_SENSOR_RTC)
#define PROSTOKONT_BOARD_POWER_FEATURES                                           \
  (BOARD_POWER_USB | BOARD_POWER_BATTERY | BOARD_POWER_PANEL_GATE)
#define PROSTOKONT_FIRMWARE_MODEL "prostokont-inkplate-13"
#elif defined(CONFIG_WAVESHARE_BOARD_WAVESHARE13)
#define PROSTOKONT_BOARD_PANEL_HEADER "panels/waveshare/Waveshare13.h"
#define PROSTOKONT_BOARD_PANEL_CLASS Waveshare13
#define PROSTOKONT_BOARD_KEY "waveshare-13.3-e6"
#define PROSTOKONT_BOARD_NAME "Waveshare 13.3 inch E6"
#define PROSTOKONT_PANEL_KEY "waveshare-13.3-e6-panel"
#define PROSTOKONT_PANEL_MANUFACTURER "Waveshare"
#define PROSTOKONT_PANEL_MODEL "13.3 inch E6 Spectra"
#define PROSTOKONT_PANEL_WIDTH_MM 203
#define PROSTOKONT_PANEL_HEIGHT_MM 270
#define PROSTOKONT_PANEL_COLOR_KIND PANEL_COLOR_KIND_PALETTE
#define PROSTOKONT_PANEL_PARTIAL_UPDATE_SUPPORTED 0
#define PROSTOKONT_BOARD_COLOR_SCHEME "6-color"
#define PROSTOKONT_BOARD_COLOR_IMAGE 1
#define PROSTOKONT_BOARD_PACKED_FRAME_SUPPORTED 1
#define PROSTOKONT_BOARD_DEFAULT_ROTATION 0
#define PROSTOKONT_BOARD_PREFER_REDUCED_DITHER 1
#define PROSTOKONT_BOARD_ACCENT_COLOR WAVESHARE13_BLUE
#define PROSTOKONT_BOARD_ERROR_COLOR WAVESHARE13_RED
#define PROSTOKONT_BOARD_COMMUNICATION_PROTOCOLS                                  \
  (BOARD_PROTOCOL_SPI | BOARD_PROTOCOL_BLE | BOARD_PROTOCOL_WIFI_STA |           \
   BOARD_PROTOCOL_WIFI_SOFTAP | BOARD_PROTOCOL_HTTP | BOARD_PROTOCOL_MDNS)
#define PROSTOKONT_BOARD_SENSORS 0u
#define PROSTOKONT_BOARD_POWER_FEATURES (BOARD_POWER_USB | BOARD_POWER_PANEL_GATE)
#define PROSTOKONT_FIRMWARE_MODEL "prostokont-waveshare-13.3e6"
#else
#error "No display board selected. Choose a board in menuconfig -> Display Board."
#endif

#if PROSTOKONT_BOARD_COLOR_IMAGE
#define COLOR_IMAGE
#endif

#include PROSTOKONT_BOARD_PANEL_HEADER
