/**
 * @file        main.cpp
 * @author      Fran Fodor for Soldered
 * @brief       Example showing how to display an image on Inkplate 2
 *              using the Soldered Image Converter tool.
 *
 * @details      This example demonstrates how to use the Soldered Image
 *              Converter to prepare an image for display on Inkplate 2.
 *              The tool converts any image into a C byte array stored in
 *              a header file (.h) which can be directly included in your
 *              Arduino sketch.
 *
 *              Tool workflow:
 *              1. Open the Image Converter at
 * https://tools.soldered.com/tools/image-converter/
 *              2. Upload your image and select "Inkplate 2" as the target
 * board.
 *              3. Choose the display mode:
 *                 - Color mode — black, white, and red
 *              4. Adjust dithering, resize, and other options as needed.
 *              5. Save the generated header file (image.h) and place it
 *                 in the same folder as this sketch.
 *
 * Requirements:
 * - Board:      Soldered Inkplate 2
 * - Framework:  ESP-IDF v6.x
 * - Hardware:   Inkplate 2, USB cable
 * - Extra:      The image header file (image.h) generated by the tool
 *
 * Configuration:
 * - Menuconfig -> Display Board -> Inkplate2
 *
 * How to use:
 * 1) Generate image.h using the Image Converter at
 * https://tools.soldered.com/tools/image-converter/ 2) Place image.h in the
 * same folder as this sketch. 3) Build and flash to Inkplate 2. 4) The image
 * appears on the display after initialization.
 *
 * Expected output:
 * - Your converted image displayed on the Inkplate 2 e-paper screen.
 *
 * Notes:
 * - image_w and image_h are automatically defined in the generated image.h.
 * - display.clearDisplay() clears only the internal framebuffer.
 * - display.display() must be called to push the framebuffer to the screen.
 *
 * Docs:         https://docs.soldered.com/inkplate
 * Support:      https://forum.soldered.com/
 * Image tool:   https://tools.soldered.com/tools/image-converter/
 */

#include "sdkconfig.h"

#ifndef CONFIG_INKPLATE_BOARD_INKPLATE2
#error                                                                         \
    "Wrong board selection for this example, please select Inkplate2 in the boards menu."
#endif

#include "Inkplate.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "image_ex.h"

extern "C" void app_main(void) {
  Inkplate display;

  display.clearDisplay(); // Clear frame buffer of display
  // Display selected picture at location X=0, Y=0. All three pictures have
  // resolution of 800x600 pixels
  display.image.draw(image, 0, 0, image_w, image_h, BLACK);
  display.display(); // Refresh the screen with new picture
}